### ISSUE TITLE
[ not an issue, question ] How to localize words « caps, num, scroll » ?

### ISSUE THREAD

**Issue by Coeur-Noir** [adrianiainlam/indicator-keyboard-led#1]
Hi,
it really is a detail ;-)
I'd prefer to see the words « caps, num, scroll » in my language ( french here ).
Where may I change that ?
Caps → Maj. → M
Num → Num. → N
Scroll → Défil. → D

Thanks a lot for that useful indicator !

**Comment by adrianiainlam** [comment]
Hi,
Thanks for supporting this project.
I have added localization support, and attempted to add translations to French.
If your system locale is set to French, the new version should (hopefully) display French by default.
If not, you can specify the locale before starting the command, e.g. `LANGUAGE=fr_FR python3 indicator-keyboard-led`.

This is my first time doing i18n/l10n so please comment here if it doesn't work and I'll try to fix it.
I also don't know French so if there's anything wrong with the translation please let me know.

Thank you very much.

**Comment by Coeur-Noir** [comment]
It seems ok to me, regarding localization, thanks a lot ! ( no need to specify LANGUAGE in command )

« Scroll » seems still broken even after adding 
`include "level3(ralt_switch)"`
into
`/usr/share/X11/xkb/symbols/fr`
And I can't manage to have it automatically started with session. What is the command to put in « applications at startup » ?
`python3 "~/path_to/indicator-keyboard-led.py --order NC"`

---

ok, found it, it's
`python3 "/home/path_to/indicator-keyboard-led.py" --order NC`

---

And just for all to know : if you're affected by a bug with physical led on keyboards which remain off even if caps or num are locked, indicator-keyboard-led is not affected and always display the actual right state of caps or num lock !

**Comment by adrianiainlam** [comment]
For scroll lock it seems like you misunderstood. You should not add `include "level3(ralt_switch)"`.

First undo what you did to /usr/share/X11/xkb/symbols/fr (i.e. restore the original version).

Then find the line that says `xkb_symbols "basic" {`. For example my file looks like this:

```
default  partial alphanumeric_keys
xkb_symbols "basic" {

    include "latin"

    name[Group1]="French";

    key <AE01>  { [ ampersand,          1,  onesuperior,   exclamdown ] };
    key <AE02>  { [    eacute,          2,   asciitilde,    oneeighth ] };
    key <AE03>  { [  quotedbl,          3,   numbersign,     sterling ] };

    ...

    key <AB08>  { [ semicolon,     period, horizconnector,   multiply ] };
    key <AB09>  { [     colon,      slash, periodcentered,   division ] };
    key <AB10>  { [    exclam,    section, dead_belowdot, dead_abovedot ] };

    include "level3(ralt_switch)"
};
...
```

Add the line `modifier_map Mod3   { Scroll_Lock };` before `include "level3(ralt_switch)"`. So at last it should look like this:

```
default  partial alphanumeric_keys
xkb_symbols "basic" {

    include "latin"

    name[Group1]="French";

    key <AE01>  { [ ampersand,          1,  onesuperior,   exclamdown ] };
    key <AE02>  { [    eacute,          2,   asciitilde,    oneeighth ] };
    key <AE03>  { [  quotedbl,          3,   numbersign,     sterling ] };

    ...

    key <AB08>  { [ semicolon,     period, horizconnector,   multiply ] };
    key <AB09>  { [     colon,      slash, periodcentered,   division ] };
    key <AB10>  { [    exclam,    section, dead_belowdot, dead_abovedot ] };

    modifier_map Mod3   { Scroll_Lock };

    include "level3(ralt_switch)"
};
...
```

Save the file (remember to open the file as root). Then run `sudo dpkg-reconfigure xkb-data`. Then log out and log in again.

**Comment by Coeur-Noir** [comment]
Sorry, my mistake in quoting !

My file looks exactly as yours.

I wonder. There are many keyboards description in that « fr » file. I use « french (alternative) » line 127 and following. Should I place `modifier_map Mod3 { Scroll_Lock } ;` in that area ?

**Comment by Coeur-Noir** [comment]
I did place `modifier_map Mod3 { Scroll_Lock } ;` in the « french (alternative) » area.
Now the led keyboard works if I hit the « arrêt défil » key.
But running `python3 indicator-keyboard-led` answers to me

```
gerald@Asgard:~/Sources et Scripts/indicator-keyboard-led-master$ python3 indicator-keyboard-led.py 
Traceback (most recent call last):
  File "indicator-keyboard-led.py", line 123, in <module>
    IndicatorKeyboardLED(short=args.short, order=args.order)
  File "indicator-keyboard-led.py", line 60, in __init__
    self.update_indicator(keymap, order)
  File "indicator-keyboard-led.py", line 91, in update_indicator
    state = keymap.get_scroll_lock_state()
AttributeError: 'gtk.gdk.X11Keymap' object has no attribute 'get_scroll_lock_state'
gerald@Asgard:~/Sources et Scripts/indicator-keyboard-led-master$
```

_By the way I don't really care about that « scroll » key - I don't even know how to use it !_

**Comment by adrianiainlam** [comment]
`get_scroll_lock_state` is only available since GTK version 3.18. Maybe your installed GTK version is older.

If you don't actually need Scroll lock, you can just add `--order NC` after the command to ignore Scroll lock.

For other people, if you really need Scroll lock, you may have to consider upgrading your system. Currently, the earliest Ubuntu release that supports GTK 3.18 is Xenial (16.04).

**Comment by adrianiainlam** [comment]
Thank you for reporting this. I have added the GTK version requirement to README.

Merci.

**Comment by Coeur-Noir** [comment]
Indeed… Ubuntu 14.04 here with libgtk 3.10 ;-)

Merci à toi !
