### ISSUE TITLE
Provide package?

### ISSUE THREAD

**Issue by ChillarAnand** [adrianiainlam/indicator-keyboard-led#2]
It would be easier for users to install from PPA. Thoughts?

**Comment by adrianiainlam** [comment]
Sounds like a good suggestion. I will need to learn how to make a debian package first, and perhaps I will take this opportunity to make the code more robust, so it may take a few days.

**Comment by adrianiainlam** [comment]
Done.
```
sudo add-apt-repository ppa:adrianiainlam/indicator-keyboard-led
sudo apt-get update
sudo apt-get install indicator-keyboard-led
```
Please report any bugs or problems found. Thanks.

**Comment by ChillarAnand** [comment]
Thanks for quick fix. Wont it bebetter to drop .py in deb package?

**Comment by adrianiainlam** [comment]
Ok. Should be fixed now.
