### ISSUE TITLE
error on Xubuntu 18.10

### ISSUE THREAD

**Issue by easyw** [adrianiainlam/indicator-keyboard-led#3]
Hi, I was trying to install this nice plugin onto xubuntu 18.10
I downloaded the zip repo and tested changing icon and local folder to the place in which are located after unzipping the folder, and the APP creates the Panel entry, bu I get the following error:
cmd:
`python3 ~/Downloads/indicator-keyboard-led-master/indicatoreyboard-led.py --short --order NC`
error:
`(indicator-keyboard-led.py:15946): Gdk-CRITICAL **: 14:16:16.319: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`
I googled around without finding a solution...
Do you think would be possible to fix this?
thanks
Maurice

**Comment by adrianiainlam** [comment]
Hello. Thanks for reminding me that I forgot to produce new packages for the new distros...

I have just created packages for bionic and cosmic on the PPA.
I then had a xubuntu 18.10 virtual machine (live CD), installed the indicator from the PPA and the indicator started without the error.
So perhaps you can try that.
The only problem for me was that only the indicator *icon* was shown -- the *label* was missing, making the indicator pointless... Please report back whether it works for you. Thanks.

**Comment by easyw** [comment]
Hi and thank you for the prompt reply.
I tested the package from the repo but unfortunately I have the same issue:
`(indicator-keyboard-led:8056): Gdk-CRITICAL **: 17:28:53.305: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

**Comment by easyw** [comment]
it seems something related to AppIndicator3 and xubuntu within my vga card installation...
