### ISSUE TITLE
Outside Unity → indicator-keyboard-led in Budgie

### ISSUE THREAD

**Issue by Coeur-Noir** [adrianiainlam/indicator-keyboard-led#4]
Hi,

I love this keyboard indicator because it allows to change state of Caps / Num on click which is very useful with remotely accessed desktops !

So I installed it on a Ubuntu Budgie 18.04.

It's totally functional but looks a bit weird : 
- lock icon is too big,
- colors of indicators look the wrong way ( it looks on while it's off / looks off while it's on )
![Capture du 2019-04-18 12-00-30](https://user-images.githubusercontent.com/1895947/56354422-f355f000-61d3-11e9-8ed1-fd8e6b2a586f.png)
Maybe it's just a matter of « styling » icons ( size, colors… ) what do you think ?

And for reference on Budgie forum : https://discourse.ubuntubudgie.org/t/improvement-for-lock-keys-indicator/1745/3

**Comment by adrianiainlam** [comment]
Thanks for your report.

Unfortunately I have exams coming up soon so I won't be able to look into this until after a few weeks.

Meanwhile, here's something you can try (file locations assume you installed from the PPA):

As root, start a text editor and open the file `/usr/share/icons/hicolor/scalable/apps/indicator-keyboard-led.svg`

Go to lines 12 and 13 where it says:

```
   width="48px"
   height="48px"
```

and change 48 to 22 (as per your Budgie forum discussion), or try other sizes until it looks good.

Next, (again as root) open the file `/usr/bin/indicator-keyboard-led`

Go to line 109 where it says

     labels += [('⚫' if state else '⚪') + self.locks[i]]

and switch the order of the two dots, i.e. `'⚪' if state else '⚫'`.

Then perhaps log out and log back in again to see if it changes.

Please report back on whether these workarounds work.

**Comment by Coeur-Noir** [comment]
Thank for your answer !

Regarding the « dots » it's ok by switching them.

Regarding the icon, changing size from 48px to 22px on lines 12 and 13 does not seem to resize icon itself but only the area through which it appears : 
![Capture du 2019-04-18 23-09-18](https://user-images.githubusercontent.com/1895947/56391619-7a848180-622f-11e9-94f2-34f4deeb03ed.png)

I wish you all the best for your exams - read : don't waste time with me ;-)

**Comment by adrianiainlam** [comment]
Try to replace the icon file with this: https://gist.githubusercontent.com/adrianiainlam/3fc8ddb7f47699691598f433016a4f44/raw/3125f6cf3d4e96476d7d84a9f95cf7fe5089b316/indicator-keyboard-led.svg

And thanks :)

**Comment by Coeur-Noir** [comment]
Ooops, I have played with the icon in inkscape - to have it 18px height into a 22px square…
and it's quite ok ;-)
![Capture du 2019-04-18 23-57-35](https://user-images.githubusercontent.com/1895947/56393838-c803ed00-6235-11e9-890f-b4b748be69f3.png)
I'm gonna try with yours.

**Comment by adrianiainlam** [comment]
I was also just trying to resize it in inkscape, yours should be very similar to mine.

**Comment by Coeur-Noir** [comment]
Indeed !
![Capture du 2019-04-19 00-04-44](https://user-images.githubusercontent.com/1895947/56394203-d1418980-6236-11e9-94e2-d168b4a56e98.png)
Different colors I will try …thank you again !

Example svg → https://gist.githubusercontent.com/Coeur-Noir/ad376f63b77cf3bfe10ad90608e4df25/raw/152958eb9554a60dfdace97020211a8a7149f8fd/indicator-keyboard-led.svg it's finally 16px height and color is a kind of grey cfd8dc to match Budgie's.
![Capture du 2019-04-19 00-18-36](https://user-images.githubusercontent.com/1895947/56397490-3e0f5080-6244-11e9-8778-b1f9aac7fbb6.png)
