### ISSUE TITLE
Errors in xubuntu 20.04

### ISSUE THREAD

**Issue by felichas** [adrianiainlam/indicator-keyboard-led#6]
Hi,

I am having problems on a new xubuntu 20.04 installation. Localization is es_ES.

First execution crashed badly due to localization templates missing. 
I had a look at the `.mo` file and it is a binary, so I tried to solve the issue by creating a symbolic link:
`cd /usr/share/locale/es/LC_MESSAGES && sudo ln -s ../../en/LC_MESSAGES/indicator-keyboar-led.mo indicator-keyboar-led.mo`.
With this it started, but it missbehaves.

Then I read your comment on issue #1  and started it with `LANGUAGE=en_EN python3 /usr/bin/indicator-keyboard-led`, and the behaviour seems to be the same:
- I can only see a padlock with an `A`, but nothing for NumLock/ScrLk. I tried with `--order NC` too.
- Pressing CAPS Lock does not change the icon, but the change takes effect when typing. Same for NumLock.
- I get the context menu with 2 or 3 options (depending on `--order`) and Quit option. All the menu items work and type  small caps or uppercase as expected, but the icon does not get updated.

BTW, I also started with indicator-keylock and moved on to your's, as I felt it was missing NumLock and I have an extended keyboard :^)

Regards,

**Comment by adrianiainlam** [comment]
This indicator is known to not work since Xubuntu 18.10. See my first comment on #3:

> The only problem for me was that only the indicator *icon* was shown -- the *label* was missing, making the indicator pointless...

I believe the problem is in xfce. See the following bug report in xfce4-statusnotifier-plugin:

> Some apps, such as SafeEyes, use AppIndicator and set a label of their indicator.
> This label is not handled by statusnotifier-plugin.

https://bugzilla.xfce.org/show_bug.cgi?id=14759
https://gitlab.xfce.org/panel-plugins/xfce4-statusnotifier-plugin/-/issues/5

The bug was reported in 2018 but still not fixed, and they will be deprecating xfce4-statusnotifier-plugin in the future:

> As of xfce 4.15, the functionality provided by xfce4-statusnotifier-plugin
has been integrated into the xfce4-panel's systray. Going forward, this plugin
is considered to be deprecated.

https://gitlab.xfce.org/panel-plugins/xfce4-statusnotifier-plugin

So I think it is very unlikely that the xfce people will fix it.

**Comment by felichas** [comment]
I guess there is nothing to do on this one, then.
Thanks a lot for your prompt support.

I can do a MR with a change in README.md to save time to the next folk comming from xubuntu. 

I normally use mate and it has a built-in option for keyboard-led indicators. But I am now configuring a laptop with xubuntu and found out there is nothing for xfce.

**Comment by adrianiainlam** [comment]
Added this as a known issue in README.

**Comment by adrianiainlam** [comment]
Also added to PPA description.

**Comment by felichas** [comment]
Just to confirm, I gave xubuntu 21.04 a go and it doesn't work, as expected.

The [release notes](https://wiki.xubuntu.org/releases/21.04/release-notes) confirm "The StatusNotifier and Systray plugins have been merged and replaced with the StatusTray plugin".
The new StatusTray has now an option to allow elements that are _not square_.

And this is the error I get when running it:
```
$ LANGUAGE=en_EN python3 /usr/bin/indicator-keyboard-led
Traceback (most recent call last):
  File "/usr/bin/indicator-keyboard-led", line 37, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Also, when installing `indicator-keyboard-led_1.1.2-3_all.deb` it with `dpkg -i` the ncurses configuration menu seemed natural to me. This was not the case when I installed it graphically (double click)... I thought the first configuration window was a popup window that came out with errors.

Regards,

**Comment by adrianiainlam** [comment]
try something like `sudo apt install gir1.2-appindicator3-0.1`?

**Comment by felichas** [comment]
Indeed, that dependency was needed. Cheers.

It now runs without errors:
```
$ LANGUAGE=en_EN python3 /usr/bin/indicator-keyboard-led
/usr/bin/indicator-keyboard-led:62: DeprecationWarning: Gdk.Keymap.get_default is deprecated
  keymap = Gdk.Keymap.get_default()
```

But with the behaviour observed in all xfce versions since xubuntu 18.10, as described in this issue.
Checking or unchecking the new "square" option makes no difference.
![imagen](https://user-images.githubusercontent.com/12903484/124273592-7d35cd80-db40-11eb-871e-80adcf7632c0.png)

Regards,

**Comment by adrianiainlam** [comment]
I've made a new re-design so that it works on xfce where indicator labels are not shown.
Just an FYI, feel free to try it if you're still interested, else just ignore this message.
