### ISSUE TITLE
'does not support jammy'

### ISSUE THREAD

**Issue by dagleykd** [adrianiainlam/indicator-keyboard-led#7]
Just tried to install this on Linux Mint 21.1 as my Dell wireless keyboard on my home theatre PC doesn't have indicator LEDs for caps/scroll/Numlock...

When I try to add the respository:
sudo add-apt-repository ppa:adrianiainlam/indicator-keyboard-led

I just get the error:
Cannot add PPA: ''This PPA does not support jammy''.

Is there a chance this will ever be updated for use on newer Ubuntu-based installs?

**Comment by adrianiainlam** [comment]
I've added packages for Jammy. However, most new non-Unity-based Ubuntus seem to not support text labels in their indicators anymore (it only shows the icon), making the indicator rather pointless (as discussed in #3). And that's kind of the reason I've stopped maintaining this.

You are free to try it (*), and if you can get the label to show, please do let me know.
If not, unfortunately there's not much I can do.

If you really can't live without this, one way this could work is to create 3 separate indicators, one for each lock.

----
(*): You would need to run `sudo apt install gir1.2-appindicator3-0.1` as well.

**Comment by adrianiainlam** [comment]
I've just pushed a new version that does not use labels, and instead uses separate icons to show the lock key statuses.
You can check the updated README for some screenshots.

Please give it a try. I'll close this issue for now, but if you experience any problems with the new version, please feel free to either reopen this issue, or raise a new one.

Thanks.

**Comment by dagleykd** [comment]
> I've just pushed a new version that does not use labels, and instead uses separate icons to show the lock key statuses. You can check the updated README for some screenshots.
> 
> Please give it a try. I'll close this issue for now, but if you experience any problems with the new version, please feel free to either reopen this issue, or raise a new one.
> 
> Thanks.

Cool, thanks friend! I'll take a look! :)

**Comment by dagleykd** [comment]
Just gave it a try and works perfectly, thanks so much! :)
